### ISSUE TITLE
Getting "Survey content list is missing" error on saved xml

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#10]
I saved the xml generated from the Survey Editor (here is the xml https://drive.google.com/file/d/0B7svGEyR3-FbdENlUE9zVHhHbms/view?usp=sharing) and was trying to upload it to the front end but I'm getting error "Survey content list is missing"
![capture](https://cloud.githubusercontent.com/assets/1034174/6136348/d8d7d63a-b124-11e4-953f-17c8ef015757.PNG)

**Comment by jeroen** [comment]
Good catch!! Turns out `contentList` is case sensitive (not `contentlist`). I fixed it, can you try again, see if it now generates a proper mixed case `contentList`?

**Comment by ctrance** [comment]
fixed
