### ISSUE TITLE
Saving xml on IE 11 (windows7) just opens blank page

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#11]
When I click 'save xml' button on IE, the browser just opens a new blank page
![capture](https://cloud.githubusercontent.com/assets/1034174/6136879/56df0090-b129-11e4-8b6c-281a6b0df933.PNG)

**Comment by jeroen** [comment]
Looks like IE doesn't support data-url: http://caniuse.com/#feat=datauri. I'll try to find a workaround.

**Comment by jeroen** [comment]
Should be fixed now.

**Comment by ctrance** [comment]
It's fixed now.
