### ISSUE TITLE
campaign info fields

### ISSUE THREAD

**Issue by jeroen** [mobilizingcs/author#12]
The ohmage server documentation says these fields are optional (o):

> (o) description = A description of the campaign.
> (o) campaign_urn = The URN for this new campaign. This may be a parameter instead of in the XML, but if it is in both places it must match exactly.
> (o) campaign_name = The name for this new campaign. This may be a parameter instead of in the XML, but if it is in both places it must match exactly.

However according to @hongsudt and @ctrance they are actually required.

**Comment by stevenolen** [comment]
they are only optional if you provide the fields in the xml, per https://github.com/ohmage/server/issues/510

**Comment by jeroenooms** [comment]
Ah ok I thought it was either one or the other.

**Comment by jeroen** [comment]
According to the [campaign definition](https://github.com/ohmage/server/wiki/Campaign-Definition#campaign) at least the URN field should be optional:

> Beginning with 2.16 it is now optional when creating a campaign if the `campaign_urn` parameter is given; however, when the definition is returned, this field will be present.

Is that correct? It would be great if we can leaven the URN out of the XML and auto generate something on the application level.

**Comment by jeroen** [comment]
Also none of the [xml files that we use for the teacher tool](https://github.com/mobilizingcs/teacher/tree/master/xml) contain any campaign info, so i'm pretty sure those fields are not required in the xml if you pass them as http parameters.

**Comment by stevenolen** [comment]
If you pass them as parameters, they do not have to be in the xml. But they
are required as parameters if the xml does not have them -- the server
won't just make up a name and urn for the campaign

**Comment by stevenolen** [comment]
look! a ghost :ghost: !

**Comment by jeroen** [comment]
Haha this has been implemented :)
