### ISSUE TITLE
single choice prompt type error

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#13]
The generated prompt type for single choice is incorrect, it should be <promptType>single_choice</promptType>. Please check other prompt types too if you're generating it correctly.

![capture](https://cloud.githubusercontent.com/assets/1034174/6157597/903686b4-b1f7-11e4-91d1-5fba723c198b.PNG)

**Comment by jeroen** [comment]
Thanks for catching that. That is a very poor parsing/error message on the server side btw.

**Comment by jeroen** [comment]
This should be fixed now.
