### ISSUE TITLE
Import xml not importing all surveys

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#14]
@jeroenooms - I was importing this xml which has multiple surveys https://drive.google.com/file/d/0B7svGEyR3-FbM0dPRXZid2NOVUk/view?usp=sharing. The import didn't show all surveys but only the first 2 surveys

**Comment by jeroen** [comment]
Thanks. It looks like there is some sort of unsupported prompt type in there that the tool is choking on. I'll investigate.

**Comment by jeroen** [comment]
This XML file contains an undocumented and unsupported prompt type `hours_before_now`. Not sure what to do with this @stevenolen @hongsudt.

**Comment by hongsudt** [comment]
hours_before_now type is supposed to be deprecated...

To handle this case, what about when you encounter an unknown prompt type,
you pop up a alert box telling users about these types and that the tool
will ignore them. If they want to proceed, click ok.. otherwise, cancel/do
nothing?

**Comment by jeroen** [comment]
Yes that is what I did.

**Comment by ctrance** [comment]
@jeroenooms - I got '...not supported' pop up twice (firefox 36.0.1 on windows) then submitting the campaign I got error missing promptID for the unsupported prompt. The app still inserts some parts of prompt for unsupported type.
![capture](https://cloud.githubusercontent.com/assets/1034174/6807863/53a42940-d20e-11e4-90fc-788e541031df.PNG)
