### ISSUE TITLE
Choice default value accepts negative number

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#16]
@jeroenooms - Per Hongsuda, "the default allows a negative number. Can we dynamically set the range to the option setting?"

I think it would be better if you change from number input to number list for the choice 
![capture](https://cloud.githubusercontent.com/assets/1034174/6944775/7477d382-d84a-11e4-85a7-bcf51e05e6ff.PNG)

**Comment by jeroen** [comment]
Force positive numbers: https://github.com/mobilizingcs/author/commit/cddbd01174ecc9851030b5daebe313d774a3bc51

**Comment by ctrance** [comment]
fixed
