### ISSUE TITLE
add warning to inform user if they do not have campaign author privileges

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/author#19]
Perhaps great to even gray out the "Edit Campaign" button on the campaign manager!

user_info/read response from server:

```
{
    "result" : "success",
    "data" : {
        "mobilize-teacher" : {
        "permissions": {
        "can_create_campaigns" : false,
        "can_create_classes" : false,
        "can_setup_users" : false,
        "is_admin" : false
    },
...
```

**Comment by stevenolen** [comment]
On second thought, we may not want to completely cut a user off from authoring a survey. I think our main goal is just to inform them that given current permissions, they will not be able to upload here (so they may not want to waste their time).  thoughts, @hongsudt ?

**Comment by hongsudt** [comment]
if they don't have the campaign creation privilege, we shouldn't let them continue.  The warning should direct them to contact their system administrator for obtaining the privilege.

**Comment by hongsudt** [comment]
@jeroenooms I would love for the users to be able to use this tool to look at the content of the campaign, even though they don't have campaign creation privilege. The tool makes it so easy, comparing to reading the xml directly.

**Comment by jeroen** [comment]
But the entire tool is made for editing. We would have to disable all of the forms and input fields and close `x` buttons and drag-drop features, etc. Otherwise the user might still be under the impression that she can edit the campaign and only find out later that the submit button is not working.

**Comment by hongsudt** [comment]
what about just disable the upload button with the tooltip that suggests
that you have no right to update the campaign?

**Comment by jeroen** [comment]
Yes we can do that, but I think it might still lead to confusion that the user has a full editing tool, but then won't be able to submit.

**Comment by jeroen** [comment]
ACL rules:
- user can **create** campaign if:
  - user is admin
  - user has campaign create privilege
- user can **update** campaign if:
  - count == 0 and user is admin
  - count == 0 and user has campaign role `author` or `supervisor`

**Comment by hongsudt** [comment]
yes. That's the rule. I just happened to work on that API yesterday to allow admin to update.

**Comment by jeroen** [comment]
OK this should now be implemented. The application will raise a warning if the user does not have sufficient privileges (based on the ACL rules above) to create or update a campaign and disable the submission button.
