### ISSUE TITLE
remove anytime flag

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#21]
I think we can remove this flag from the GUI and set it to true in the xml. Only the native android app uses this flag.. The new ohmageX app assumes anytime is always true.

**Comment by hongsudt** [comment]
@jeroenooms Can you comment this piece out from the GUI?

**Comment by jeroen** [comment]
Only for lausd or for all deployments?

**Comment by hongsudt** [comment]
all deployments, since the phone component doesn't support that yet.

Instead of deleting it, can you comment it?

**Comment by jeroen** [comment]
Fixed https://github.com/mobilizingcs/author/commit/b68fd50178efddf1808f9762d9e4acd21818d5cd.
