### ISSUE TITLE
photo prompt: add imageQuality property

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#26]
Add another an imageQuality which is a number between 0 and 100.. 

This is not currently implemented in the server yet though.. I will add this later..

**Comment by jeroen** [comment]
Fixed @ https://github.com/mobilizingcs/author/commit/9c8b611463eb0016eb3f051af899b85fb5d53f36.

**Comment by hongsudt** [comment]
@jeroenooms Sorry!  Can we change it to jpegQuality so it is more specific to jpeg?  Thanks!

**Comment by jeroen** [comment]
Done @ https://github.com/mobilizingcs/author/commit/2689fdb00f93e69248f84cfae4867d1113124819

**Comment by hongsudt** [comment]
@jeroenooms  Can you provide a tool tip to user that this number has to be between 0 and 100?

**Comment by jeroen** [comment]
https://github.com/mobilizingcs/author/commit/fa064b3a85db83e8b74724b531ffea7ad07c5cdb
