### ISSUE TITLE
audio: change max length to seconds

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#28]
Can you change the GUI to ask for maximum audio length in seconds and convert that to milliseconds in the xml, so it is consistent with video?

**Comment by jeroen** [comment]
Shouldn't you be changing this in the back-end? You don't think it's confusing that the user enters a value but some other value appears in the xml?

**Comment by jeroen** [comment]
Anyway here it is: https://github.com/mobilizingcs/author/commit/61764ad773753fb4cec20ae52a9aa9c9b4d9b86c

**Comment by stevenolen** [comment]
A backwards compatibility thing, since the feature was first written a number of versions ago and it's difficult for the server to handle both cases without making assumptions?
