### ISSUE TITLE
single/multi-choice: make sure at least one choice is defined

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#29]
Can you make sure that at least one choice is defined? 

This is not true for single- and multi-choice custom though..

**Comment by jeroen** [comment]
I'm not sure how I can force the user to enter an choice...

**Comment by hongsudt** [comment]
@jeroenooms How did you do it for the single choice custom?

**Comment by jeroen** [comment]
I haven't yet. There is no easy way to do it using standard validation techniques. The server does not require this either by the way, so technically speaking, a choice prompt with 0 options is valid :)

**Comment by jeroen** [comment]
Okay I think I actually found a way to hack this in :bowtie: https://github.com/mobilizingcs/author/commit/2d20b10166872c75c184bbdfd01bfbc87b13e270. 

The tagit choice widget should light up if there are zero options (though the server doesn't enforce this).

**Comment by hongsudt** [comment]
cool!

FYI: I will look into the server validation this week and will let you know
fixes that I can do.

Thanks!

**Comment by jeroen** [comment]
OK closing this issue for now.
