### ISSUE TITLE
add default value to applicable prompt types

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#3]

**Comment by ctrance** [comment]
Missing default value for prompts below:
-number
-text
-single/multi choice
-custom choice

**Comment by jeroen** [comment]
It already supports `<default>` for number prompts. I haven't seen the `<default>` been used in text/choice prompts in the example campaigns. Is this a critical feature for deployment or nice to have?

**Comment by jeroen** [comment]
I have added the 'default' field for x-choice prompts. The only tricky thing is that this field itself is optional because sometimes you specifically do not want to set a default, correct?

**Comment by hongsudt** [comment]
Correct.  the default field is optional. It is optional for all prompts.

Can you detect whether a value is entered? If so, it has to be validated
and added to xml. Otherwise, it should not be included in the xml.

**Comment by ctrance** [comment]
@jeroenooms - There's still no 'default' field for text prompt.

**Comment by jeroen** [comment]
Fixed at https://github.com/mobilizingcs/author/commit/f90fda0e58c95e49b34466de7f3bc08e86185228.

**Comment by ctrance** [comment]
tested and it's fixed
