### ISSUE TITLE
move "enable syntax highlighting" location? 

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#31]
When I observed an lausd teacher using the app, she didn't pay attention to that checkbox at all since it is toward the end of the page.. I am wondering whether we should move this flag up, so it can easily catch user's attention.. But I am not sure where we can move it to..

**Comment by jeroen** [comment]
Fixed @ https://github.com/mobilizingcs/author/commit/3cabdf4fec0da3c1210ded62a312cb28baf96968

**Comment by hongsudt** [comment]
@jeroenooms The current location is nice!!
