### ISSUE TITLE
allow configuration of allowed prompt type

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#33]
On lausd, we want to only allow the first group of the prompt type and hide the rest.. On the sandbox or other servers, we probably want everything to be shown. Can we make this configurable on lausd?

**Comment by jeroen** [comment]
How would you like to configure this? Via some sort of config file, or just by looking at the hostname?

**Comment by stevenolen** [comment]
We do this in some other frontends by looking at the hostname. Not the most beautiful but it leaves everyone except those visiting at `lausd.mobilizingcs.org` with the same experience. (and it's easy enough to grep these projects for that domain name if we need to change in the future.

**Comment by jeroen** [comment]
That is kind of ugly. Maybe we should add a flag to `/app/config/read` if this is a simplified deployment or so?

**Comment by stevenolen** [comment]
We actually already have an application name param in that api output if you want to use it: 

``` json
{
  "result": "success",
  "data": {
    "survey_response_privacy_states": [
      "private",
      "shared"
    ],
    "application_build": "d9424cd",
    "user_setup_enabled": true,
    "application_name": "mobilize",
    "mobility_enabled": false,
    "default_campaign_creation_privilege": true,
    "application_version": "2.18.0",
    "auth_token_lifetime": 900000,
    "maximum_parameter_size": 1073741824,
    "default_survey_response_sharing_state": "private",
    "self_registration_allowed": true,
    "maximum_request_size": 1099956224
  }
}
```

`"application_name": "mobilize"`

**Comment by jeroen** [comment]
Does lausd have a unique `application_name` ?

**Comment by stevenolen** [comment]
yes...and no! we only have one production server that uses that name, but `test.mobilizingcs.org` also uses this etc.

**Comment by jeroen** [comment]
OK so I guess it's easiest to just look at the hostname. Fixed @ https://github.com/mobilizingcs/author/commit/a81ff3eada1d5b82eb807d5e14fdf6bc557223ff. Can't really test this without deploying though :D

**Comment by hongsudt** [comment]
This is good for now... But if lausd takes over, they will likely be running it on a different server with different hostname though.  In this case, maybe going with the app name is more flexible?

**Comment by stevenolen** [comment]
we have a number of other apps etc that do this, so handling it all at once is probably best :)

**Comment by jeroen** [comment]
HT says we should switch this to a server flag.

**Comment by stevenolen** [comment]
You can use `application_name` will do! mobilize and ohmage are the only support ones at the moment!

https://github.com/mobilizingcs/author/issues/33#issuecomment-161669720

**Comment by jeroen** [comment]
Fixed in https://github.com/mobilizingcs/author/commit/d15aa338fad22305277ae9424035c41ca9d8594b. We are now looking at the `application_name == "mobilize"`. Note that as a result, the advanced prompt types are no longer showing up on mtest either because this server has the same application name. Perhaps we should change that.
