### ISSUE TITLE
asterisk next to required fields?

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/author#35]
It's not particularly clear when creating a campaign which fields are required (such as the description field for survey).  This is caught when the user attempts to upload, but it would be nice to more readily see this as inputs are shown to user.

Since there is a bit of input overload, it would be nice at a glance for the user to know which ones weren't as important in order to prevent overwhelming them.

**Comment by jeroen** [comment]
I think pretty much everything is required? You really think adding asterisks to almost every input field will make things clearer?

**Comment by stevenolen** [comment]
I think with a long campaign/survey, it's really tough as a user when you try to submit and get missing required field alerts like that. You have to track back to the survey, find the prompt that has the missing thing and fix it.  Would be nicer if we could highlight those items or do something to handle required items a little better than just an alert box from the server on submit.

**Comment by jeroen** [comment]
Missing required fields now get highlighted in red.
