### ISSUE TITLE
add close button to prompt popover

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/author#37]
It isn't particular natural to have to click the prompt "button" again in order to close this popover, but it would likely be annoying to have it close whenever another element is clicked.  Perhaps adding a "X" or "close" button to the popover would make a more actionable item for users to realize they could click to close the popover?

**Comment by jeroen** [comment]
There was a reason i didn't do this, but i forgot what it was. So I guess we'll do it again. BTW you can also close popovers by hitting `ESC`.

**Comment by jeroen** [comment]
Ah i remember now, for some reason bootstrap does not capture 'click' events inside the popover. Anyway I hacked around it, hopefully this works https://github.com/mobilizingcs/author/commit/00b0cdc822d0baee0facd5939c3a9b2ba59a8029.

**Comment by stevenolen** [comment]
works in chrome!
