### ISSUE TITLE
add missing prompt types

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#4]
- single-choice custom 
- multi-choice custom 
- video
- audio

**Comment by jeroen** [comment]
Done

**Comment by jeroen** [comment]
It's getting a little bloated for my taste now. Perhaps we need an option that we can hide some of the prompt types for deployments where they are not used.

**Comment by hongsudt** [comment]
I like the idea of making available prompt type configurable.. but from the
feature perspective, we need to implement the authoring interface for all
prompt types. I assign this to a different milestone, so it is not part of
the first release.  It is there to remind you.. So don't close it, but tag
it differently.
