### ISSUE TITLE
Text min/max length validation didn't work

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#41]
@jeroenooms - On text prompt I entered min length of 5 then max length 0, app submitted the campaign.

**Comment by jeroen** [comment]
I know, dynamic validation is a bit difficult to implement because the validity of one field can change depending on the other. Hopefully most users will understand that max has to be greater than min once they see this error.

**Comment by hongsudt** [comment]
@jeroenooms I added this validation to the server.

**Comment by jeroen** [comment]
Added a visual hint on the client as well: https://github.com/mobilizingcs/author/commit/62137b90105d439ee411964258940c6825e8de88

**Comment by ctrance** [comment]
fixed
