### ISSUE TITLE
Max file size needs specific info

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#42]
@jeroenooms - Video and audio has specific info on its max length which is "(in seconds)". Can you please do the same in file prompt?
![capture](https://cloud.githubusercontent.com/assets/1034174/11661590/8652f1d8-9d87-11e5-9985-734e7c645445.PNG)

**Comment by jeroen** [comment]
I'm waiting for @hongsudt to tell me what the unit for filesize is.

**Comment by hongsudt** [comment]
@jeroenooms The unit is in bytes..

**Comment by jeroen** [comment]
ok done

**Comment by ctrance** [comment]
fixed
