### ISSUE TITLE
Can't access add prompt modal on FF

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#43]
@jeroenooms - On FF, If I have added couple of prompts which would make me scroll at the bottom the page when adding new prompt, the add prompt modal don't show the rest of the prompt types.
![capture](https://cloud.githubusercontent.com/assets/1034174/11662389/35843e0c-9d8b-11e5-831b-1fec9557871a.PNG)

**Comment by jeroen** [comment]
Thanks. I have temporarily disabled the affix scroll until we've found a solution for this: https://github.com/mobilizingcs/author/commit/2fd5fa4c1d6985bfe622f3571f7f5f670468ce27

**Comment by ctrance** [comment]
fixed
