### ISSUE TITLE
number prompt: default value validation

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#44]
When I check a wholeNumber to true and enter a decimal for the default value, even though the app highlight the wrong default value area in red (which is cool), if I go ahead and click submit, it will allow me to go ahead and submit.. 

If there is a failed validation, shouldn't it pop up an error message instead of allowing the campaign to be submitted?  In this case, since there is a server bug, the campaign submission is successful which is kind of confusing..

**Comment by jeroen** [comment]
No, the client only highlights individual fields that might be incorrect, but only the server can determine if an xml submission in its entirety is acceptable.
