### ISSUE TITLE
add "editable responses" parameter to campaign states

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/author#47]
as of https://github.com/ohmage/server/issues/888 we now support editable survey responses where applicable.  

Please add a toggle-able parameter which sets `editable: true/false` (default false) on the author tool.

Additionally! It would be best if this could be hidden if `app_name = mobilize` as this brings some serious downsides to participatory sensing studies.

**Comment by jeroen** [comment]
So is this an xml field or a parameter in campaign/create ?

**Comment by stevenolen** [comment]
param in `campaign/create`

**Comment by jeroen** [comment]
Can you add that to the wiki docs?

**Comment by stevenolen** [comment]
done!
https://github.com/ohmage/server/wiki/Campaign-Manipulation

**Comment by jeroen** [comment]
Done and done: https://github.com/mobilizingcs/author/commit/33239365c676816d88a7bff0bbb37109bb81b9fe, https://github.com/mobilizingcs/author/commit/0c138f4948b7d929697daf6efb44784fed2c879e. Let me know if this is what you had in mind.

**Comment by stevenolen** [comment]
yessir! thanks much!
