### ISSUE TITLE
make xml area scrollable

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/author#6]

**Comment by hongsudt** [comment]
@jeroenooms can we make the xml part scrollable instead of making the whole page scrollable? This will make it easier to view the xml and edit the campaign at the same time..

**Comment by jeroen** [comment]
We still need to be able scroll the left part of the page as well, so that would result in a double scroll bar...

**Comment by jeroen** [comment]
I tried to solve it in a different way, with an affix. So now you can scroll down the xml, but the menu stays in the screen. This allows for viewing the xml and menu at the same time without nested scroll bars.

**Comment by hongsudt** [comment]
Neat!!

**Comment by hongsudt** [comment]
@jeroenooms I like this!
