### ISSUE TITLE
Add skip label field if 'skippable' box is checked

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#7]
If user checked 'skippable' box allow user to enter customized skip label.

**Comment by ctrance** [comment]
@jeroenooms - This is still missing on the current version, please add.

**Comment by jeroen** [comment]
We decided that this is not a deployment critical feature and perhaps not a useful feature at all.

**Comment by ctrance** [comment]
@hongsudt - Should I leave this open for the next deployment or just close this issue?

**Comment by jeroen** [comment]
Let's close it. We can reopen if we change our mind

**Comment by hongsudt** [comment]
ohmageX currently doesn't support this.. Will close this for now..
