### ISSUE TITLE
Add condition

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#8]
Right now I can't add condition(s) to the prompt, please add it.

**Comment by ctrance** [comment]
@jeroenooms - There's still no way to add condition(s) to prompts. Please add that.

**Comment by jeroen** [comment]
I've added basic support for conditions. For now you have to enter the condition yourself.

**Comment by jeroen** [comment]
@hongsudt I have been testing this a bit and found that the server-side validation on conditions is actually very good. It prints helpful error messages when an invalid condition is entered. I think this solution is very workable for now.

**Comment by jeroen** [comment]
Conditions can be added for each prompt and the server does a good job in validating the syntax. I think we should leave it like this.

**Comment by hongsudt** [comment]
@jeroenooms  Then let's add some tooltip to help guide the users on how to write it? I assume that you converted `>` to `&gt;` ?

**Comment by jeroen** [comment]
@hongsudt escaping/unescaping of text is done when converting to/from xml. This is done for all fields, not just condition.

**Comment by jeroen** [comment]
I updated the tooltip a bit with some examples...

**Comment by ctrance** [comment]
@jeroenooms - The tool tip message looks good but can you make the tool tip more intuitive? Maybe add "?" icon so user would know that when they hover over there will be a tool tip.

**Comment by jeroen** [comment]
@ctrance OK have added that, let me know if this is more intuitive.

**Comment by ctrance** [comment]
@jeroenooms - Looks very intuitive, thanks! I'm closing this :)
