### ISSUE TITLE
Adding single choices is not user friendly

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/author#9]
![capture](https://cloud.githubusercontent.com/assets/1034174/6134998/f4692c74-b119-11e4-9dd1-201799e95146.PNG)
On FF 35.0.1 (windows7), I have to click other fields to add new choice. Maybe have a '+' icon that enables user to add new choice right away or always have a blank row at the end?

**Comment by ctrance** [comment]
Ahh if I enter it adds the choice :)

**Comment by jeroen** [comment]
Yes, just type a value and hit `enter`. Click the little `x` to remove a value.
